/**
 * Quick Init Command — Fast-track project setup
 *
 * Creates a BookForge project with sensible defaults
 * in under 30 seconds.
 */

import fs from 'node:fs';
import path from 'node:path';
import { initProject } from '../installer/installer.js';
import { exists, writeJson, writeText, mkdir } from '../../runtime/core/io.js';

/**
 * Quick initialization with minimal questions
 *
 * @param {string} projectDir - Project directory
 * @param {object} options - Configuration options
 * @returns {object} Project configuration
 */
export async function quickInit(projectDir, options = {}) {
  const {
    topic,
    audience,
    genre,
    bookType,
    yes = false
  } = options;

  // Auto-detect or default values
  const config = {
    project: projectDir,
    template: detectTemplate(topic, genre, bookType),
    host: 'auto',
    graph: 'none',
    bookType: bookType || 'General Book',
    yes: yes,
    metadata: {
      topic,
      audience,
      detected_genre: genre,
      quick_init: true,
      initialized_at: new Date().toISOString()
    }
  };

  // Initialize the project
  await initProject(projectDir, config);

  // Override with quick-init specific settings
  await applyQuickInitOverrides(projectDir, config);

  return config;
}

/**
 * Detect the best template based on topic and preferences
 */
function detectTemplate(topic, genre, bookType) {
  if (genre) return genre;
  if (bookType === 'Fiction') return 'fiction-thriller';
  if (bookType === 'Nonfiction') return 'nonfiction-business';
  if (bookType === 'Memoir') return 'memoir';

  // Auto-detect from topic keywords
  const t = (topic || '').toLowerCase();
  if (/thriller|mystery|crime|suspense/.test(t)) return 'fiction-thriller';
  if (/business|entrepreneur|startup|money|marketing/.test(t)) return 'nonfiction-business';
  if (/memoir|autobiography|life story|personal/.test(t)) return 'memoir';
  if (/self.?help|personal development|productivity|habits/.test(t)) return 'nonfiction-business';

  return 'default';
}

/**
 * Apply quick-init specific overrides
 */
async function applyQuickInitOverrides(projectDir, config) {
  // Enable auto-revision in config
  const configPath = path.join(projectDir, 'bookforge.yaml');
  if (exists(configPath)) {
    let content = require('fs').readFileSync(configPath, 'utf8');
    // Add quick-init optimizations
    content = content.replace(
      /quality:\n(  .*\n)*/,
      `quality:
  require_human_gate_before_release: true
  fail_on_unresolved_critical_findings: true
  auto_correct_severity: [low, medium]
  max_revision_cycles: 3\n`
    );
    require('fs').writeFileSync(configPath, content);
  }

  // Create quick-start guide
  const guidePath = path.join(projectDir, 'QUICKSTART.md');
  const guideContent = `# BookForge Quick Start

## Your Project
- **Topic**: ${config.metadata.topic || 'Not specified'}
- **Audience**: ${config.metadata.audience || 'General'}
- **Template**: ${config.template}
- **Initialized**: ${config.metadata.initialized_at}

## Next Steps

### 1. Define Your Book Contract
Run: \`bookforge run book-contract\`

### 2. Create Your Outline
Run: \`bookforge run outline\`

### 3. Start Drafting
Run: \`bookforge pipeline run\` to automatically draft all chapters

### 4. Review and Refine
Run: \`bookforge validate\` to check quality

## Key Commands

| Command | Purpose |
|---------|---------|
| \`bookforge status\` | View project status |
| \`bookforge validate\` | Run quality checks |
| \`bookforge pipeline run\` | Auto-draft all chapters |
| \`bookforge run chapter-plan\` | Plan next chapter |
| \`bookforge run draft-chapter\` | Draft specific chapter |

## Tips
- Start with \`bookforge pipeline run --chapter-start 1 --chapter-end 3\` to test the pipeline
- Use \`--dry-run\` to preview changes before applying
- Check \`bookforge/quality/reports/\` for detailed quality findings
`;
  writeText(guidePath, guideContent);

  // Create initial state files if missing
  const stateDir = path.join(projectDir, 'bookforge', 'state');
  mkdir(stateDir);

  const contractPath = path.join(stateDir, 'book-contract.md');
  if (!exists(contractPath)) {
    const contractContent = `# Book Contract

## Title
[Enter your book title]

## Author
${config.metadata.topic || '[Author name]'}

## Genre
${config.template}

## Target Audience
${config.metadata.audience || 'General readers interested in this topic'}

## Central Promise
[What will the reader gain from this book?]

## Tone
[Choose: mentor, companion, investigator, storyteller, teacher, witness]

## Target Length
[Total words or chapters]

---
Generated by BookForge Quick Init
`;
    writeText(contractPath, contractContent);
  }
}

// CLI entry point
export async function main(args) {
  const projectDir = args[1] || process.cwd();
  const topic = args.find(a => a.startsWith('--topic='))?.split('=')[1] ||
                args.find(a => a.startsWith('--topic '))?.split(' ')[1];
  const audience = args.find(a => a.startsWith('--audience='))?.split('=')[1] ||
                   args.find(a => a.startsWith('--audience '))?.split(' ')[1];
  const genre = args.find(a => a.startsWith('--genre='))?.split('=')[1] ||
                args.find(a => a.startsWith('--genre '))?.split(' ')[1];
  const bookType = args.find(a => a.startsWith('--book-type='))?.split('=')[1] ||
                   args.find(a => a.startsWith('--book-type '))?.split(' ')[1];
  const yes = args.includes('--yes') || args.includes('-y');

  console.log('🚀 BookForge Quick Init');
  console.log('========================');
  console.log(`Project: ${projectDir}`);
  console.log(`Topic: ${topic || 'Not specified'}`);
  console.log(`Audience: ${audience || 'General'}`);
  console.log(`Template: ${genre || bookType || 'Auto-detected'}`);
  console.log('');

  try {
    const config = await quickInit(projectDir, {
      topic,
      audience,
      genre,
      bookType,
      yes
    });

    console.log('✅ Project created successfully!');
    console.log('');
    console.log('Next steps:');
    console.log('  1. bookforge run book-contract');
    console.log('  2. bookforge run outline');
    console.log('  3. bookforge pipeline run');
    console.log('');
    console.log('See QUICKSTART.md for detailed instructions.');

    return config;
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

export default { quickInit, detectTemplate };
